### ISSUE TITLE
no exported member 'BaseServiceOptions'.

### ISSUE THREAD

**Issue by craigharman** [hexenq/nest-gitlab#6]
When I try and use the package I get the error:

```
node_modules/nest-gitlab/dist/gitlab.interfaces.d.ts:2:10 - error TS2305: Module '"../../@gitbeaker/core/dist/types/infrastructure"' has no exported member 'BaseServiceOptions'.

2 import { BaseServiceOptions } from '@gitbeaker/core/dist/types/infrastructure';
```

**Comment by hexenq** [comment]
nest-gitlab 3.0.0 has been released and it may solve this issue. You could also check [the compatibility table](https://github.com/hexenq/nest-gitlab#compatibility) to decide which version of nest-gitlab you should use.
